# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4efb93430b5721736a69dc7162f1ba79fea32e58688099964e8c9992ec60f435c6bc22f2c32a92e6f0eff8ebc25404c66567272a1c26c8a7397c7a675ed8006

test:
  secret_key_base: 0269209ff6549c827f99adc581637e2c31b0ee98a41e55bdcd831480a427646c87505cf60b3e532f91c25630a5b1b81cf0784f976bf7230ed692401196033310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
